api/pom.xml, api/src/main/java/ca/bc/gov/educ/api/ruleengine/config/GradCommonConfig.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/config/RequestInterceptor.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/util/LogHelper.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/util/RuleEngineApiConstants.java, api/src/main/resources/application.yaml, api/src/test/resources/application.yaml, tools/openshift/api.dc.yaml
Splunk logging is initially implemented.
=> Splunk logging is initially implemented.

api/pom.xml, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/AdultStudentGradeRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/util/RuleProcessorUtils.java
New rule for 1950 Adult program 
https://gww.jira.educ.gov.bc.ca/browse/GRAD2-1560
=> New rule for 1950 Adult program - JIRA GRAD2-1560

api/pom.xml, api/src/main/java/ca/bc/gov/educ/api/ruleengine/dto/GraduationProgramCode.java, api/src/test/resources/2018-EN-126187616.json
GRAD2-1614 : removed assessmentReleaseDate.
=> GRAD2-1614 : removed assessmentReleaseDate.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/DuplicateCoursesRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/RestrictedCoursesRule.java
GRAD2-1653 - Adult (1950) graduation algorithm and course restriction
=> GRAD2-1653 and GRAD2-1684

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/DuplicateAssessmentsRule.java
GRAD2-1733 - Student "clob" for Adult (1950) and 2004 students not showing all assessment data
=> GRAD2-1733 - Student "clob" for Adult (1950) and 2004 students not showing all assessment data

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinAdultCoursesRule.java
GRAD2-1760 - Adult Graduatiol Algorithm and "carry-forward" courses
=> GRAD2-1760 - Adult Graduation Algorithm and "carry-forward" courses

.github/workflows/on.pr.yml, Dockerfile, api/pom.xml, api/src/main/java/ca/bc/gov/educ/api/ruleengine/config/RequestInterceptor.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/config/WebSecurityConfiguration.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/util/LogHelper.java
Upgraded rule engine api to spring boot 3.0.2
=> Upgrade API to Spring boot 3.0.2

.github/workflows/build.from.main.branch.deploy.to.dev.yml, .github/workflows/build.from.release.branch.deploy.to.dev.yml, .github/workflows/deploy_prod.yml, .github/workflows/deploy_test.yml, Dockerfile, api/src/main/resources/application.yaml, tools/openshift/api.dc.yaml
GRAD2-1947 - Openshift Resource Optimization for GRAD APIs
=> GRAD2-1947 - Openshift Resource Optimization for GRAD APIs

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/AlgorithmSupportRule.java
GRAD2-1871 - When Adult (1950) students have no eligible courses their Non Grad reasons are wonky
=> GRAD2-1871 - When Adult (1950) students have no eligible courses

api/pom.xml, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/AlgorithmSupportRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MatchCredit1996Rule.java
=> Grad release 1.8.32

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/AlgorithmSupportRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/OptionalProgramMatchRule.java
… Arts 10 (english) for DD - need 4-credits
=> GRAD Release 1.8.38

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MatchCredit1986Rule.java
GRAD2-2035 - Update Consumer Ed Flag requirement logic for Grade 10 level course
=> GRAD2-2035 - Update Consumer Ed Flag requirement logic for Grade 10

api/pom.xml, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/OptionalProgramNoRule.java
GRAD2-2149 - 2023 Graduation Program not setting 951, 952 and 953 optional program requirements met properly
=> GRAD2-2149 - 2023 Graduation Program not setting 951, 952 and 953

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/EquivalencyRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinCreditsElective12OtherRule.java
GRAD2-2161: task is completed.
=> GRAD2-2161: task is completed.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/RegistrationsDuplicateCrseRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/util/RuleEngineApiUtils.java
GRAD2-2162: task is completed.
=> GRAD2-2162: task is completed.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinElectiveCreditsRule.java
GRAD2-2165 - 2023 Program - not graduating students with 80 Credits
=> GRAD2-2165 - 2023 Program - not graduating students with 80 Credits

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MatchIndigenousCreditsRule.java
GRAD2-2153 - 2023 Program - Split-credits and the new Indigenous-focused requirement
=> GRAD2-2153 - 2023 Program - Split-credits and the new Indigenous-focused requirement

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/AssessmentsMatchCreditsRule.java
=> GRAD2-2158: task is complete.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MatchCredits1950Rule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MatchCreditsRule.java
GRAD2-2195 - 1950 Program algorithm choosing math 12 over math 11 and preventing graduation
=> GRAD2-2195 - 1950 Program algorithm

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MatchCredits2023Rule.java
GRAD2-2198 - 2023 GRAD Program Issues
=> GRAD2-2198 - 2023 GRAD Program Issues

api/src/main/java/ca/bc/gov/educ/api/ruleengine/util/RuleProcessorRuleUtils.java
GRAD2-2272: task is completed.
=> GRAD2-2272: task is completed.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinAdultCoursesRule.java
GRAD2-2271: task is completed.
=> GRAD2-2271: task is completed.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/DuplicateCoursesRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinAdultCoursesRule.java
GRAD2-2271: improved for a student with "X" courses and regular courses.
=> GRAD2-2271: improved for a student with "X" courses and regular courses.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/dto/StudentCourse.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MatchCredit1996Rule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinCredit1996Rule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinElectiveCredits1996Rule.java
=> GRAD2-2023: task is complete.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/EquivalencyRule.java
=> GRAD2-2417: task is complete.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinElectiveCredits1996Rule.java
GRAD2-2023: fixed the sorting order in minElectiveCredits1996Rule.
=> GRAD2-2023: fixed the sorting order in minElectiveCredits1996Rule.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinElectiveCredits2023Rule.java
=> GRAD2-2454: task is complete.

api/pom.xml
=> Grad release 1.12.0

README.md
* Update README.md
* Update README.md
* Update README.md
=> Sync from main (#465)

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MainProgramCompleteRule.java
=> GRAD2-2467: task is complete.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MainProgramCompleteRule.java
GRAD2-2467: the duplicate optional nonGradReasons issue is resolved.
=> GRAD2-2467: the duplicate optional nonGradReasons issue is resolved.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/AssessmentRegistrationsRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/IncompleteAssessmentsRule.java
=> GRAD2-2503: task is complete.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/CareerProgramMatchRule.java
=> GRAD2-2509: task is complete.

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinAdultCoursesRule.java
GRAD2-2947 - P3 - GRAD System - Adult Course Session DD needs to be set to 01 to compare with Adult Start Date
=> GRAD2-2947 - P3 - GRAD System - Adult Course Session DD

api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MatchCreditsRule.java, api/src/main/java/ca/bc/gov/educ/api/ruleengine/rule/MinAdultCoursesRule.java
GRAD2-2947: hot fixes on comparing course session with adult start date.
=> GRAD2-2947: hot fixes on comparing course session with adult start date.

.github/dependabot.yml, .github/workflows/build.from.developer.branch.deploy.to.dev.yml, .github/workflows/build.from.main.branch.deploy.to.dev.yml, .github/workflows/build.from.release.branch.deploy.to.dev.yml
=> Grad2-3138 ZAPscan version upgraded

api/src/main/java/ca/bc/gov/educ/api/ruleengine/dto/School.java
GRAD2-2761: districtId is newly added into School Clob.
=> GRAD2-2761: districtId is newly added into School Clob.

tools/openshift/api.dc.yaml
GRAD2-3307 - Remove reference to api-student-graduation-db-secret from deployment file
=> GRAD2-3307 - Remove reference to api-student-graduation-db-secret from deployment file
